version: '3.8'
volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  app:
    image: sriramasunkara02/app:latest
    ports:
       - '8080:8080'
    environment:
       - 'spring.profile.active=test'
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - app:app
    depends_on:
      - app
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    links:
            - prometheus